### ISSUE TITLE
codes in the lstlisting disorder when crossing pages

### ISSUE THREAD

**Issue by dcalsky** [SXKDZ/tongjithesis#1]
When using `lstlisting` and codes cross two pages, lots of vertical lines appear in the page. And a word, included in the code, will appear in the right-bottom and top-left corners of the page.

## Page 1
left side of page:
<img width="156" alt="image" src="https://user-images.githubusercontent.com/9463958/58630996-b4a76f80-8313-11e9-812b-46f5265730ef.png">

right-bottom of the page:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/9463958/58631018-c557e580-8313-11e9-8fa1-cf97e6d7280f.png">

## Page 2
<img width="535" alt="image" src="https://user-images.githubusercontent.com/9463958/58631050-e4567780-8313-11e9-8827-380fc4c4fef1.png">

**Comment by SXKDZ** [comment]
won't fix /::| /::D /::<

**Comment by Alraemon** [comment]
lstlisting sucks, recommend using minted package, here's my configuration.

```latex
\RequirePackage[chapter]{minted}	% listings sucks, use minted
\RequirePackage{mdframed}
\mdfdefinestyle{codebox}{
	leftmargin=3em,
	rightmargin=3em,
	innertopmargin=1em,
	innerbottommargin=1em,
	linewidth=0.6pt
}
\newminted{python}{
	linenos=true,
	breaklines=true,
	breakanywhere=true,
	frame=none,
	python3=true,
	fontsize=\zihao{5},
	numbersep=2em,
	style=default,
	tabsize=2,
	xleftmargin=0.5em,
	xrightmargin=0.5em,
	}
\renewcommand{\theFancyVerbLine}{\rmfamily \textcolor{gray}{\zihao{5} \oldstylenums{\arabic{FancyVerbLine}}}} 
```

modify tongjithesis.cls to replace lstlisting

**Comment by Alraemon** [comment]
and remember using these environments in tex
```latex
\begin{mdframed}[style=codebox]
\begin{pythoncode}
balabala
\end{pythoncode}
\end{mdframed}
```

**Comment by Alraemon** [comment]
and of course, no more this strange issue.
![截屏2020-07-09 下午4 22 28](https://user-images.githubusercontent.com/28785891/87015821-7fe93580-c200-11ea-8d9f-b2ddccfc518b.png)

**Comment by SXKDZ** [comment]
@Alraemon Many thanks. Would you please send me a pull request?
