### ISSUE TITLE
在overleaf里编译不出来

### ISSUE THREAD

**Issue by siiyizhang** [SXKDZ/tongjithesis#6]
学长们你们好，我是18级环境科学的本科生，在网上看到了这个毕业论文模板想在overleaf里用。一开始的编译器是pdfLaTex然后会报错，所以换成了XeLaTex，但直到time out还是一直编译不出来，想问一下我是有什么地方设置的不对，或者是哪里需要修改一下才能在overleaf里用吗？谢谢！

**Comment by SXKDZ** [comment]
同学你好：overleaf免费版有编译时间限制，而XeLaTeX编译比较慢，正常情况下的确无法编译出来。你可以选择本地编译或者使用付费版的overleaf

**Comment by siiyizhang** [comment]
谢谢！免费试用了专业版overleaf还是编译不出来，转用Texmaker了……秒速编译
